import { useFormik } from "formik";
import * as yup from "yup";

export const useServiceFormValidationSchema = (onSubmit) => {
  const serviceFormInitialValues = {
    facilityName: "",
    lga: "",
    state: "",
    clientName: "",
    patienttId: "",
    sex: "",
    artStartDate: "",
    ageAtArtStart: "",
    telephone: "",
    dateEnrolledIntoOtz: "",
    OtzPlus: "",
    baselineViralLoadAtEnrollment: "",
    dateDone: "",
    acMonth1EacDate1: "",
    acMonth1EacDate2: "",
    acMonth1EacDate3: "",
    acMonth2EacDate1: "",
    acMonth2EacDate2: "",
    acMonth2EacDate3: "",
    acMonth3EacDate1: "",
    acMonth3EacDate2: "",
    acMonth3EacDate3: "",
    vlMonth1Date: "",
    vlMonth1Result: "",
    vlMonth2Date: "",
    vlMonth2Result: "",
    vlMonth3Date: "",
    vlMonth3Result: "",

    maMonth1PositiveLivingDate: "",
    maMonth1PositiveLivingChoice: "",
    maMonth1LiteracyTreatmentDate: "",
    maMonth1LiteracyTreatmentChoice: "",
    maMonth1AdolescentsParticipationDate: "",
    maMonth1AdolescentsParticipationChoice: "",
    maMonth1leadershipTrainingDate: "",
    maMonth1leadershipTrainingChoice: "",
    maMonth1PeerToPeerDate: "",
    maMonth1PeerToPeerChoice: "",
    maMonth1RoleOfOtzDate: "",
    maMonth1RoleOfOtzChoice: "",
    maMonth1OtzChampionOrientationDate: "",
    maMonth1OtzChampionOrientationChoice: "",

    maMonth2PositiveLivingDate: "",
    maMonth2PositiveLivingChoice: "",
    maMonth2LiteracyTreatmentDate: "",
    maMonth2LiteracyTreatmentChoice: "",
    maMonth2AdolescentsParticipationDate: "",
    maMonth2AdolescentsParticipationChoice: "",
    maMonth2leadershipTrainingDate: "",
    maMonth2leadershipTrainingChoice: "",
    maMonth2PeerToPeerDate: "",
    maMonth2PeerToPeerChoice: "",
    maMonth2RoleOfOtzDate: "",
    maMonth2RoleOfOtzChoice: "",
    maMonth2OtzChampionOrientationDate: "",
    maMonth2OtzChampionOrientationChoice: "",

    maMonth3PositiveLivingDate: "",
    maMonth3PositiveLivingChoice: "",
    maMonth3LiteracyTreatmentDate: "",
    maMonth3LiteracyTreatmentChoice: "",
    maMonth3AdolescentsParticipationDate: "",
    maMonth3AdolescentsParticipationChoice: "",
    maMonth3leadershipTrainingDate: "",
    maMonth3leadershipTrainingChoice: "",
    maMonth3PeerToPeerDate: "",
    maMonth3PeerToPeerChoice: "",
    maMonth3RoleOfOtzDate: "",
    maMonth3RoleOfOtzChoice: "",
    maMonth3OtzChampionOrientationDate: "",
    maMonth3OtzChampionOrientationChoice: "",

    sixMonthsResult: "",
    sixMonthsDate: "",
    twelveMonthsResult: "",
    twelveMonthsDate: "",
    eighteenMonthsResult: "",
    eighteenMonthsDate: "",
    twentyFourMonthsResult: "",
    twentyFourMonthsDate: "",
    thirtyMonthsResult: "",
    thirtyMonthsDate: "",
    thirtySixMonthsResult: "",
    thirtySixMonthsDate: "",

    chooseOutcomes: null,
    exitedOtz: "",
    transitionDate: "",
    
    viralLoadOnOtzExit: "",
    dateOfAssessmentDone: "",
    exitedByName: "",
    exitedByDesignation: "",
    exitedByDate: "",
    exitedBySignature: "",
  };

  const ServiceFormValidationSchema = yup.object().shape({
    facilityName: yup.string(),
    lga: yup.string(),
    state: yup.string(),
    clientName: yup.string(),
    patienttId: yup.string(),
    sex: yup.string(),
    artStartDate: yup.string(),
    ageAtArtStart: yup.string(),
    telephone: yup.string(),
    dateEnrolledIntoOtz: yup.string(),
    OtzPlus: yup.string(),
    baselineViralLoadAtEnrollment: yup.string(),
    dateDone: yup.string(),

    acMonth1EacDate1: yup.string(),
    acMonth1EacDate2: yup.string(),
    acMonth1EacDate3: yup.string(),

    acMonth2EacDate1: yup.string(),
    acMonth2EacDate2: yup.string(),
    acMonth2EacDate3: yup.string(),

    acMonth3EacDate1: yup.string(),
    acMonth3EacDate2: yup.string(),
    acMonth3EacDate3: yup.string(),

    vlMonth1Date: yup.string(),
    vlMonth1Result: yup.string(),
    vlMonth2Date: yup.string(),
    vlMonth2Result: yup.string(),
    vlMonth3Date: yup.string(),
    vlMonth3Result: yup.string(),

    maMonth1PositiveLivingChoice: yup.string(),
    maMonth1PositiveLivingDate: yup.string(),
    maMonth1LiteracyTreatmentChoice: yup.string(),
    maMonth1LiteracyTreatmentDate: yup.string(),
    maMonth1AdolescentsParticipationChoice: yup.string(),
    maMonth1AdolescentsParticipationDate: yup.string(),
    maMonth1leadershipTrainingChoice: yup.string(),
    maMonth1leadershipTrainingDate: yup.string(),
    maMonth1PeerToPeerChoice: yup.string(),
    maMonth1PeerToPeerDate: yup.string(),
    maMonth1RoleOfOtzChoice: yup.string(),
    maMonth1RoleOfOtzDate: yup.string(),
    maMonth1OtzChampionOrientationDate: yup.string(),
    maMonth1OtzChampionOrientationChoice: yup.string(),
    


    maMonth2PositiveLivingDate: yup.string(),
    maMonth2PositiveLivingChoice: yup.string(),
    maMonth2LiteracyTreatmentDate: yup.string(),
    maMonth2LiteracyTreatmentChoice: yup.string(),
    maMonth2AdolescentsParticipationDate: yup.string(),
    maMonth2AdolescentsParticipationChoice: yup.string(),
    maMonth2leadershipTrainingDate: yup.string(),
    maMonth2leadershipTrainingChoice: yup.string(),
    maMonth2PeerToPeerDate: yup.string(),
    maMonth2PeerToPeerChoice: yup.string(),
    maMonth2RoleOfOtzDate: yup.string(),
    maMonth2RoleOfOtzChoice: yup.string(),
    maMonth2OtzChampionOrientationDate: yup.string(),
    maMonth2OtzChampionOrientationChoice: yup.string(),

    maMonth3PositiveLivingDate: yup.string(),
    maMonth3PositiveLivingChoice: yup.string(),
    maMonth3LiteracyTreatmentDate: yup.string(),
    maMonth3LiteracyTreatmentChoice: yup.string(),
    maMonth3AdolescentsParticipationDate: yup.string(),
    maMonth3AdolescentsParticipationChoice: yup.string(),
    maMonth3leadershipTrainingDate: yup.string(),
    maMonth3leadershipTrainingChoice: yup.string(),
    maMonth3PeerToPeerDate: yup.string(),
    maMonth3PeerToPeerChoice: yup.string(),
    maMonth3RoleOfOtzDate: yup.string(),
    maMonth3RoleOfOtzChoice: yup.string(),
    maMonth3OtzChampionOrientationDate: yup.string(),
    maMonth3OtzChampionOrientationChoice: yup.string(),

    sixMonthsResult: yup.string(),
    sixMonthsDate: yup.string(),
    twelveMonthsResult: yup.string(),
    twelveMonthsDate: yup.string(),
    eighteenMonthsResult: yup.string(),
    eighteenMonthsDate: yup.string(),
    twentyFourMonthsResult: yup.string(),
    twentyFourMonthsDate: yup.string(),
    thirtyMonthsResult: yup.string(),
    thirtyMonthsDate: yup.string(),
    thirtySixMonthsResult: yup.string(),
    thirtySixMonthsDate: yup.string(),

    chooseOutcomes: yup.array(),
    exitedOtz: yup.string(),
    transitionDate: yup.string(),

    viralLoadOnOtzExit: yup.string(),
    dateOfAssessmentDone: yup.string(),
    exitedByName: yup.string(),
    exitedByDesignation: yup.string(),
    exitedByDate: yup.string(),
    exitedBySignature: yup.string(),
  });

  const formik = useFormik({
    initialValues: serviceFormInitialValues,
    onSubmit,
    validationSchema: ServiceFormValidationSchema,
  });
   return { formik };;
};



